env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/tomozo6/uma/cmd.Version={{.Version}}
      - -X github.com/tomozo6/uma/cmd.Revision={{.ShortCommit}}
    goos:
      - linux
#     - darwin
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
#      darwin: Darwin
      linux: Linux
#      windows: Windows
      386: i386
      amd64: x86_64
#    format_overrides:
#    - goos: windows
#      format: zip
release:
  prerelease: auto
